-- Generated by nwg-displays on 2026-09-03 at 20:35:14. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1"
})
